server:
  port: 8888

spring:
  application:
    name: fisheriz-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/technoavi/fisheriz-config-server
          clone-on-start: true


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka










