spring:
  application:
    name: fisheriz-config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/technoavi/fisheriz-config-server

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/




